# Generated by Django 3.0.5 on 2020-04-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_image',
        ),
    ]
